client/src/App.css, client/src/App.tsx
모든 화면에서 공유할 CSS Global Style 세팅
1) box-sizing : border-box
2) margin : 0px (엘리멘트 기본 margin 값 제거)
3) list-style : none
=> [Design] #20 CSS Global Style 세팅

server/008main_project/.github/workflows/main.yml, server/008main_project/Dockerfile
-Dockerfile 생성
-main.yml 파일 생성
Issues #8
=> [Feat] 백엔드 서버 CI 구현

client/src/components/StockOrderSection/Index.tsx, client/src/components/StockOrderSection/PriceSetting.tsx, client/src/reducer/StockOrderPrice-Reducer.ts, client/src/store/config.ts, client/tsconfig.json
- AWS 서버 업로드위한 빌드 중 발견된 오류코드 수정
- 상세내역) 일부 import 경로명 불일치, 선언 되었으나 사용되지 않은 변수 존재
- 이외 변경사항) tsconfig.json 파일에 빌드 경로 추가 ( ./dist )
=> [Fix] 빌드 관련 버그코드 수정

.idea/.name, server/008main_project/src/main/java/com/stockholm/main_project/auth/filter/JwtAuthenticationFilter.java, server/008main_project/src/main/java/com/stockholm/main_project/auth/mail/AccountController.java, server/008main_project/src/main/java/com/stockholm/main_project/auth/mail/Dto/ConfirmPostDto.java, server/008main_project/src/main/java/com/stockholm/main_project/auth/mail/Dto/SendEmailPostDto.java, server/008main_project/src/main/java/com/stockholm/main_project/board/Controller/BoardController.java, server/008main_project/src/main/java/com/stockholm/main_project/board/dto/BoardDto.java, server/008main_project/src/main/java/com/stockholm/main_project/board/dto/BoardPostDto.java, server/008main_project/src/main/java/com/stockholm/main_project/config/SwaggerConfig.java, server/008main_project/src/main/java/com/stockholm/main_project/member/controller/MemberController.java, server/008main_project/src/main/java/com/stockholm/main_project/member/dto/MemberPatchDto.java, server/008main_project/src/main/java/com/stockholm/main_project/member/dto/MemberPostDto.java, server/008main_project/src/main/java/com/stockholm/main_project/member/dto/MemberResponseDto.java, server/008main_project/src/main/java/com/stockholm/main_project/member/service/MemberService.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/controller/CompanyController.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/controller/StockController.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/dto/CompanyResponseDto.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/dto/StockMinResponseDto.java, server/008main_project/src/main/java/com/stockholm/main_project/swaggersample/HelloController.java, server/008main_project/src/main/resources/application.yml
open api 3.0 swagger(springdocs) 명세서 작성
=> Swagger api 명세서 추가

client/src/components/communityComponents/TimeLineComponent.tsx, client/src/main.tsx
-게시판 글작성 및 업로드 기능까지만 서버연결 했습니다
-삭제부분은 아직 서버와의 연결까지 하지 못했습니다 추후에 연결필요
=> [Feat]게시판기능 서버연결 게시판 업로드 

client/package-lock.json, client/package.json, client/src/components/MarketComponents/MarketStockList.tsx, client/src/components/MarketComponents/index.tsx, client/src/components/communityComponents/Comments.tsx, client/src/components/communityComponents/IconComponent/Icon.tsx, client/src/components/communityComponents/StockDisscussion.tsx, client/src/components/communityComponents/index.tsx, client/src/components/stockListComponents/DetailStockInformation.tsx, client/src/components/stockListComponents/StockItems.tsx, client/src/page/TabPages/MarketInfoPage.tsx, client/src/page/TabPages/TabContainerPage.tsx, client/src/page/TabPages/communityPage.tsx
-탭 상단부분 아이콘 추가 
-Market부분 뉴스 바로가기 버튼 부분 디자인 일부 수정 추가 작업 필요 
-Community 의 종목토론부분 종목 리스트 나열 및 일부 디자인 추가 작업 필요
-종목 정보부분의 이미지는 임시이미지 서버에서 보내지는 데이터 완료되면 연동 후 추가작업 필요
=> [FE]index파일경로 수정 및 디자인

client/src/components/Headers/LoginHeader.tsx, client/src/components/Logins/EmailLogin.tsx, client/src/components/Logins/OAuthLogin.tsx, client/src/components/Signups/Password.tsx
-로그인 시 헤더에서 버튼 옆에 보이는 문자열 삭제
-로그인 성공 시 엑세스 토큰과 리프레시 토큰 저장
-로그인 post 메시지 발송 시 axios 주소 수정
-회원가입 post메시지 발송 후 백엔드에서 전송하는 메시지를 200이 아닌 201로 받음
Issues #15
=> [FE] 헤더,로그인,회원가입 통신 정상화 및 토큰 저장 Dev client#8/signuplogin

client/src/components/CentralChart/StockChart.tsx, client/src/components/StockOrderSection/Index.tsx, client/src/components/StockOrderSection/OrderDecisionBtn.tsx, client/src/components/StockOrderSection/PriceSetting.tsx, client/src/components/StockOrderSection/StockOrder.tsx, client/src/components/StockOrderSection/StockPrice.tsx, client/src/components/StockOrderSection/StockPriceList.tsx, client/src/components/StockOrderSection/VolumeSetteing.tsx, client/src/hooks/useGetKospiChart.ts, client/src/reducer/CompanyId-Reducer.ts, client/src/store/config.ts
- 주식주문 관련 거래가/거래량 키보드 입력 기능 구현
- 매수/매도 버튼 클릭 시 화면에 렌더링 되는 모달창 구현 (구매가/구매량 설정 관련 경우의 수 고려하여 구현) 
- 기존 Feature 브랜치에서 다시 분기된 브랜치이므로 리뷰 없이 merge 수행
=> [FE] 주식주문 관련 거래가/거래량 입력 기능 및 주문 관련 모달창 구현

client/package-lock.json, client/package.json, client/src/models/stockInfoProps.ts, client/tsconfig.json
- S3 서버에 업로드 하기 위해 빌드 시 오류 발생하는 코드 수정
=> [FE] 빌드 시 오류 발생하는 코드 수정

client/src/components/MarketComponents/MarketKospiChart.tsx, client/src/components/communityComponents/Comments.tsx, client/src/page/TabPages/TabContainerPage.tsx
=> [FE]빌드시 발생하는 에러수정

client/src/components/communityComponents/Comments.tsx, client/src/components/communityComponents/StockDisscussion.tsx, client/src/components/communityComponents/index.tsx, client/src/models/stateProps.ts, client/src/page/TabPages/MarketInfoPage.tsx
-바뀐 API주소 적용
-게시물 작성 POST할때 헤더에 TOKEN 넣어서 전송 Issue #84
=> [Fix] 커뮤니티기능 서버연결

client/src/page/MainPage.tsx
- 일부 컴포넌트 전환 시 메인페이지 화면에 스크롤바 생성되어 전체 레이아웃이 변동되는 문제 발생
- 이를 해결하기 위해 메인페이지 컴포넌트에 CSS 속성 추가
=> [FE] 메인페이지 레이아웃 조정

server/008main_project/src/main/java/com/stockholm/main_project/scheduler/StockScheduler.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/controller/CompanyController.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/controller/StockOrderController.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/repository/StockMinRepository.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/service/StockMinService.java, server/008main_project/src/main/java/com/stockholm/main_project/stock/service/StockOrderService.java
- 분봉차트 최근 420개 정보 반환하도록 변경
- 미체결 데이터 수량 조절 삭제로 변경
- 예약 매도 로직 수정
=> [Merge] 분봉 차트 수정, 매도, 매수 기능 로직 수정

client/src/components/StockOrderSection/OrderResult.tsx, client/src/components/StockOrderSection/StockOrder.tsx, client/src/components/communityComponents/Comments.tsx, client/src/components/communityComponents/index.tsx
- S3 서버 업로드 위한 빌드 작업 중 오류 발생하는 코드 수정
=> [Fix] 빌드 시 오류 발생하는 코드 수정

client/src/components/StockOrderSection/OrderResult.tsx, client/src/components/StockOrderSection/StockOrder.tsx, client/src/components/StockOrderSection/StockPrice.tsx, client/src/components/StockOrderSection/StockPriceList.tsx
- 체결/미체결 거래내역 창 전환 시 가장 최근 거래가 바로 보이도록 설정
=> [Feat] 거래내역 창 전환 시 최근 거래가 바로 보이도록 설정

client/src/components/EntireList/EntireList.tsx, client/src/components/HoldingList/HoldingList.tsx, client/src/components/HoldingList/StockItem.tsx, client/src/components/Logins/LoginConfirmatationModal.tsx, client/src/components/Logins/OAuthLogin.tsx, client/src/components/Profile/cashModal.tsx, client/src/components/Profile/memberWithdrawalModal.tsx, client/src/components/Profile/profileModal.tsx, client/src/components/watchlist/WatchList.tsx, client/src/hooks/useCash.ts, client/src/hooks/useDeleteMembers.ts, client/src/reducer/cash/cashSlice.ts
프로필 창에서 현금 탭을 눌렀을 때 현금 생성, 현금 확인, 현금 리셋이 정상적으로 작동하도록 구현
Issues #70
=> [FE]현금 훅, 현금 리듀서, 현금 프로필 창 오류 해결 Dev client#19/watch list

client/src/components/CentralChartMenu/ExpandScreenBtn.tsx, client/src/components/CentralChartMenu/Index.tsx, client/src/components/EntireList/EntireList.tsx, client/src/components/EntireList/Header.tsx, client/src/components/EntireList/StockItem.tsx, client/src/components/Headers/LoginHeader.tsx, client/src/components/HoldingList/Header.tsx, client/src/components/HoldingList/HoldingList.tsx, client/src/components/HoldingList/StockItem.tsx, client/src/components/StockOrderSection/OrderResult.tsx, client/src/components/watchlist/Header.tsx, client/src/components/watchlist/WatchList.tsx, client/src/hooks/useGetStockChart.ts, client/src/hooks/useGetStockOrderRecord.ts, client/src/models/stockProps.ts, client/src/page/MainPage.tsx
[ 추가 기능 ]
- 우측 주식주문의 체결 거래 관련 체결 시간 조회 가능
[ 레이아웃 / 디자인 ]
- 좌측 종목현황 부분 레이아웃 및 디자인 중앙 차트와 유사한 테마로 수정
- 전체 외곽선 색깔 검정색으로 수정
- 이외 컴포넌트 비율 안맞는 부분 수정
=> [FE] 기타 세부기능 및 레이아웃 / 디자인 수정

client/src/components/CentralChartMenu/ExpandScreenBtn.tsx, client/src/components/Headers/LogoutHeader.tsx, client/src/components/MarketComponents/MarketStockList.tsx, client/src/components/MarketComponents/index.tsx, client/src/components/StockOrderSection/Index.tsx, client/src/components/StockOrderSection/StockOrder.tsx, client/src/components/communityComponents/index.tsx, client/src/hooks/useGetStockChart.ts, client/src/page/TabPages/MarketInfoPage.tsx, client/src/page/TabPages/TabContainerPage.tsx
- 우측 컴포넌트(시장정보) 관련 컨텐츠 개수 증가에 따라 레이아웃 깨지는 현상 해결
=> [FE] 우측 컴포넌트 레이아웃 깨지는 현상 해결

client/src/components/Profile/cashModal.tsx, client/src/components/Profile/memberInfoModal.tsx, client/src/components/Profile/memberWithdrawalModal.tsx, client/src/components/Profile/profileModal.tsx, client/src/hooks/useDeleteMembers.ts, client/src/hooks/useGetCashId.ts
프로필 창에서 일어나는 버그 수정
탭 배치 수정
현금기능 직관적으로 수정
회원탈퇴기능 프론트에서는 이상 무
Issues #70
=> Dev client#19/watch list

client/src/components/communityComponents/Comments.tsx, client/src/components/communityComponents/index.tsx
- 게시판 관련하여 글 작성 컴포넌트 렌더링 시 레이아웃 깨짐 현상 수정
- 추가적으로 창닫기 버튼 디자인 수정
=> [Fix] 게시판 레이아웃 깨짐현상 해결

client/src/components/communityComponents/Comments.tsx, client/src/components/communityComponents/index.tsx, client/src/components/stockinfoComponents/stockinfoChart.tsx
=> [FE]빌드시오류 수정

client/src/components/EntireList/EntireList.tsx, client/src/components/HoldingList/HoldingList.tsx, client/src/components/MarketComponents/MarketKospiChart.tsx, client/src/components/communityComponents/index.tsx, client/src/components/stockinfoComponents/stockinfoChart.tsx, client/src/hooks/useGetMemberInfo.ts, client/src/page/MainPage.tsx
- 디자인 및 레이아웃 관련 CSS 일부 수정
- 이외 불필요한 코드 (es. console.log 등 삭제)
=> [FE] 디자인 관련 CSS 일부 수정

client/src/components/Headers/LoginHeader.tsx, client/src/components/Headers/LogoutHeader.tsx, client/src/components/MarketComponents/MarketStockList.tsx, client/src/components/watchlist/StockItem.tsx, client/src/components/watchlist/WatchList.tsx, client/src/hooks/useGetMemberInfo.ts, client/src/hooks/useGetStockInfo.ts, client/src/hooks/useTradeStock.ts, client/src/page/MainPage.tsx
로고 클릭 시 새로고침기능 추가
console.log 지속적으로 뜨는 것 몇개 삭제
종목 랭킹 색상 변경
=> [FE]잔버그 수정Dev client#19/watch list
